In [1]:
import numpy as np

#list

In [6]:
a_py = [10,20,30,40]
a_py

[10, 20, 30, 40]

In [7]:
type(a_py)

list

#NUMPY

In [8]:
b_np = np.array([10,20,30])
b_np

array([10, 20, 30])

In [9]:
type(b_np)

numpy.ndarray

#MULTIPLY 10 TO ALL ARRAY LIST


In [10]:
arr =  []
for i in a_py:
    arr.append(i * 10)

arr

[100, 200, 300, 400]

#lambda, map

In [12]:
del list

In [13]:
list(map(lambda x: x*10, a_py))

[100, 200, 300, 400]

In [14]:
[ i*10 for i in a_py]

[100, 200, 300, 400]

In [16]:
#how to resolve in np
b_np * 10

array([100, 200, 300])

#numpy less memory footprint & high performance


#numpy array contain only one datatype

In [23]:
c_np = np.array([1,2,3])  # whole np array is int64
c_np

array([1, 2, 3])

In [18]:
type(c_np)

numpy.ndarray

In [19]:
c_np.dtype

dtype('int64')

In [24]:
c_np = np.array([1,5.2,3])  # see one is float, so whole np array is float
c_np

array([1. , 5.2, 3. ])

In [21]:
type(c_np)

numpy.ndarray

In [22]:
c_np.dtype

dtype('float64')