In [16]:
import pandas as pd
import numpy as np
from sklearn import linear_model
import warnings
warnings.filterwarnings('ignore')

In [17]:
df = pd.read_csv('/home/samim/homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [18]:
df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [19]:
df.iloc[:,0:3]

area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18
3  3600       3.0   30
4  4000       5.0    8
5  4100       6.0    8

In [29]:
x = df.iloc[:,0:3].values

In [20]:
reg = linear_model.LinearRegression()
reg.fit(df.iloc[:,0:3],df.price)

LinearRegression()

In [21]:
reg.coef_


array([  112.06244194, 23388.88007794, -3231.71790863])

In [22]:
reg.intercept_


221323.00186540396

# Find price of home with 3000 sqr ft area, 3 bedrooms, 40 year old.

In [23]:
reg.predict([[3000, 3, 40]])

array([498408.25158031])

In [25]:
112.06244194 * 3000 + 23388.88007794 * 3 + -3231.71790863 * 40 +  221323.00186540384

498408.25157402386

# Find price of home with 2500 sqr ft area, 4 bedrooms, 5 year old.

In [26]:
reg.predict([[2500, 4, 5]])

array([578876.03748933])

In [27]:
112.06244194 * 2500 + 23388.88007794 * 4 + -3231.71790863 * 5 +  221323.00186540384

578876.0374840139